language: node_js
node_js:
- stable
- node
cache: yarn

stages:
- test
- name: deploy
  if: tag IS present AND repo = Cretezy/braintree-web-drop-in-react

jobs:
  include:
  - stage: deploy
    env: DEPLOY=releases
    script: yarn pack
    deploy:
    - provider: releases
      api_key:
        secure: fPLZdUTGObHWbXBytpx0yveTCONFhUGHskTPddzVVLxipLKBFjMwhTjXM6gvZ4lYHBzIy00KqGLk5katiQNOfqwnocGABRvYQW8OVciIrVr9D02Xj9QEgeMvPW0Qrf0JltyMttY4i0jt3gpXGXwGBvJy5sX5kW8TPSKY14n0muNMmCpMbSHv0DipMoStpHqTap/5teAsI/eLWMU/BOEAzHKzxhouaJI3KI6DyFEUDi4sQjT88F55ChEUhvHXLW0U1P1bEON5W9Qj41XkYzEWRMEWgvPdkCMtSYhB16NBA3cQr2hfGWOj0NVX7VZpmi93omzUbD/CWThVQbrfAjqwhoZJC/Y3nHEz2W7OxFEiI5NIg+W0DV7i4myzzEPx3aDmweiJP0xLyr+kFFf/0dCZmjwDWgaQsAoA593knpiLzKm8ACQBMXH2FT30KX16G+dmV77Gha+meru9DYr3BW4iSvH2OuLqYOOW0+ehp+A91v/tZEHcPQAZVMgobvBDU/cOn7yzwdgrsiiVNmd80MSCfBwvh3KB1G3Yto0VXSK9hRp+S1UGSINQNUdQ674A0YYFPTjz1wqA+TRDwmw25wu5b8zD2Liz2ZwS7HjgY7glBGc4DEZp86094nlVxgixfyXpYPMAeClQhUfjm7NWWxsexwAdAtb1qvNOZQ6bivgDd5Q=
      file_glob: true
      file: braintree-web-drop-in-react--*.tgz
      skip_cleanup: true
      on:
        tags: true
  - stage: deploy
    env: DEPLOY=npm
    script: skip
    deploy:
    - provider: npm
      email: charles@cretezy.com
      api_key:
        secure: Iygd0dBsRQ10xfuUQyaeHS1DoVWcl+UMgJI1J5q+YmWc46SPS1RI0oGZ75UCT1PxJKTz39yu2tiLB3q/3T41vaMel9nEm5XtOyv0PcML6LM4ak+HC7b6HGGV9B4QtBgSdDSr/H4uu40ICzAC37i6ACPN83b1EupbxMtt1YUZ7b9So8fhGdTqw+LXH1ohCFKZ7OQ+bgsSkL5u6IVOVNBpFSVxfP5zsFwjj+9HWiW/JdBtW4xgT/e03w+f/qZdclxQYJNkX24L7/6fFV7zpqbjSZXojvXtDCtZGTLsPPsP+eUX6WNTWYUi/RhWPBRFbOHgGvY83IuTe+Jkg+5NYjJiA6hG5RAiA0MOK+ZnF0yLwExDnCwhYpvbfyLIjNwnmkLIAc/b8zLJIgz+XGc4FU4U21bOao/omqzmftzTIOhODgDIQczssH0ztRvNIaBQ80wtd3ahfsBNNTIZRB5GvvJhzqQXcijPDm57XViaK5i4ymsbBhQ2Zj7U7430Q3ewwi0ZOtSQmppLdYTFiVrun5JExgLdwvGJulGL1lTk+VRTPaLcowbrx7psa5aHKB3P7co1rCeKXCt13G1PXy8L/ZLs/Cz7E9LKQc1aWbcnR1s+E3wH31pNishbBd6LrIs3hfLuqhYu1LC/q0sGt41Lea7+kIVT6OrLkdDYLk8yfoRMi70=
      skip_cleanup: true
      on:
        tags: true
